on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Check

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
