on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  schedule:
    - cron: "0 12 * * 0"

name: Check

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3

  test-run:
    name: Run VKMS
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install VKMS
      run: pip install .
    - name: Run VKMS
      run: |
        vkms -i ${{ secrets.VKMS_INCLUDE }} dump --token ${{ secrets.VKMS_ACCESS_TOKEN }} --export-json
        vkms -i ${{ secrets.VKMS_INCLUDE }} parse -f txt
        vkms -i ${{ secrets.VKMS_INCLUDE }} parse -f html
        vkms -i ${{ secrets.VKMS_INCLUDE }} atch
    - name: Zip artifacts with password
      run: zip -P '${{ secrets.ZIP_PASSWORD }}' -r result.zip vkms-result/ 1>/dev/null
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: VKMS result
        path: result.zip
        if-no-files-found: error
    - name: Clear artifacts
      run: rm -rf vkms-result/
